### ISSUE TITLE
ENH:  higher order epu energy scan capability

### ISSUE THREAD

**Issue by ambarb** [NSLS-II-CSX/undcontrol#1]
@stuwilkins can we think about adding a factor to be used to make it possible to do energy scans using the epu's 3rd harmonic?  Currently, we have to disable the interpolation table and hand enter ppm_en/3.  We can test as SIX per @bisogni

I am not sure how @irawaluyo does this at CSX-2.

**Comment by stuwilkins** [comment]
I would suggest that 3rd Harmonic should be done via a separate table. There should be an interpolation table for the 1st and one for the 3rd. You can then choose between the two by choosing the table.

This is how it is done also for the polarization…..

Does that make sense?

On Jul 13, 2017, at 4:53 PM, ambarb <notifications@github.com<mailto:notifications@github.com>> wrote:


@stuwilkins<https://github.com/stuwilkins> can we think about adding a factor to be used to make it possible to do energy scans using the epu's 3rd harmonic? Currently, we have to disable the interpolation table and hand enter ppm_en/3. We can test as SIX per @bisogni<https://github.com/bisogni>

I am not sure how @irawaluyo<https://github.com/irawaluyo> does this at CSX-2.

**Comment by irawaluyo** [comment]
We do have separate tables for the 1st and 3d harmonics.

**Comment by ambarb** [comment]
That makes perfect sense. @irawaluyo measured our first harmonic table for epu2.  @stuwilkins @cmazzoli @wen-hu do we want to measure the 3rd harmonic ourselves or see if Ira can do this before the canting magnet is changed.

**Comment by irawaluyo** [comment]
Since the two epus are supposed to be identical, you can use my 3rd harmonic table as a starting point if you want.

**Comment by ambarb** [comment]
@irawaluyo thanks.  Did you happen to compare epu1 and epu2 for the first harmonic before.  I assume that they are the same, but I know you measured ours so I assumed we needed to use it as a table.  Maybe @cmazzoli has a better recollection?  I have the results you sent for EPU2.  If you didn't compare, can you send us the EPU1 results for the first harmonic?

**Comment by irawaluyo** [comment]
There were small differences between epu1 and epu2, but maybe only around 0.1 mm or so if I remember correctly. I’ve attached the tables for 1st and 3rd harmonic for epu1, measured in 50 eV step size and interpolated with 1 eV step.
