### ISSUE TITLE
bpms.db for SIX

### ISSUE THREAD

**Issue by ambarb** [NSLS-II-CSX/undcontrol#2]
@stuwilkins I am going to update the bpms.db so that SIX also has deviation from setpoint over time.  However, it looks like you calculate the accelerator's x and y angles yourself.  Was this before the machine did so?  I had just planned on using the machines SOFB bump readback for the offset and angle and not the active interlock.  This looks roughly to be the same as the smoothed version you have in the CSX bpms.db code....perhaps you generated this code before the SOFB bump readback was even available?

Let me know if there is a more nuanced difference.

**Comment by stuwilkins** [comment]
Hi @ambarb, Yes the reason I did this was at the beginning there was too much  confusion on what the numbers were for the beam position. So, I created PVs for the actual position and angle from the BPMs to avoid any confusion. There is probably no need now.....

**Comment by ambarb** [comment]
Ok.  I used the machine's readback and not the active interlock  (slow orbit verus fast orbit).  These things are now working at SIX.
